### ISSUE TITLE
GShell + generation meets error

### ISSUE THREAD

**Issue by XiaokunSun** [lzzcd001/GShell#11]
I have obtained the result of GMeshdiffusion as shown below. How should I use the eval_gmeshdiffusion_generated_samples.py file to convert it into mesh? Your explanation in the readme is too brief, and I am missing the './data/tets/64_tets_cropped_rectified.npz' (see eval_gmeshdiffusion_generated_samples.py line 114 ). It seems that you forgot to upload something.
![image](https://github.com/user-attachments/assets/ff9f2079-39a1-4180-b27f-c4e2d2be978c)

**Comment by lzzcd001** [comment]
Thanks for pointing it out. It should be called 64_tets_cropped_reordered.npz instead, which can be download with the linked provided.

**Comment by XiaokunSun** [comment]
Thank you for your reply, but I am still experiencing the error, I get the following error when I run `python eval_gmeshdiffusion_generated_samples.py -o /root/data/SunXiaoKun/Project/GShell/outputs/generation/lower_mesh --grid_root /root/data/SunXiaoKun/Project/GShell/outputs/generation/lower --config /root/data/SunXiaoKun/Project/GShell/configs/deepfashion_mc_80.json`, I am wondering if I am missing something? Looking forward to your reply.
Error:
![image](https://github.com/user-attachments/assets/158c430d-9148-47b2-81db-6d27ab0456db)
