### ISSUE TITLE
Release the code?

### ISSUE THREAD

**Issue by chiehwangs** [lzzcd001/GShell#2]
Hi,

Very innovative work! Are there any plans to release the code?

best,
chieh

**Comment by lzzcd001** [comment]
Appreciate for your interest in our work! We plan to release the code for reconstruction in roughly a week (and it may take a bit longer for the generation part). Pin me if that does not happen.

**Comment by lzzcd001** [comment]
Sorry for being late on this and thank you for your patience - the code for reconstruction is now ready. We will upload the remaining parts in the following weeks.
