### ISSUE TITLE
Code for generative models

### ISSUE THREAD

**Issue by USTC3DV** [lzzcd001/GShell#4]
This work has been very helpful to me. May I ask when the generated code will be open-sourced?

**Comment by lzzcd001** [comment]
Thank you for your interest in our work. We are aiming for releasing the code, model weights and likely the datasets by the beginning of April.

**Comment by lzzcd001** [comment]
Really appreciate your patience - we have released the code for diffusion models (both training and inference) plus model checkpoints. The datasets will be uploaded to HuggingFace in the following days.
