### ISSUE TITLE
Segmentation fault of OptiXContext

### ISSUE THREAD

**Issue by sungmin9939** [lzzcd001/GShell#5]
Hi 

I have encountered segmentation fault while testing your work with this command `python train_gshelltet_deepfashion.py --config configs/deepfashion_mc_256.json --index 0 --trainset_path data/deepfashion3d_training_data/ --testset_path data/deepfashion3d_test_data/ --o ./result`

> DatasetNERF: 72 images with shape [1024, 1024]
DatasetNERF: 72 images with shape [1024, 1024]
DatasetNERF: 200 images with shape [1024, 1024]
/opt/conda/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392020201/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Cuda path /usr/local/cuda
Segmentation fault (core dumped)

the exact location of code that yields segmentation fault is at ` OptiXStateWrapper of render/optixutils/ops.py`

> class OptiXContext:
    def __init__(self):
        print("Cuda path", torch.utils.cpp_extension.CUDA_HOME)
        self.cpp_wrapper = _plugin.OptiXStateWrapper(os.path.dirname(__file__), torch.utils.cpp_extension.CUDA_HOME)

and here is information of my environment

> pytorch3d               0.7.5
torch                   2.1.0
torchvision             0.16.0
Cuda: 11.8
docker image:  pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel 
gcc version: 9.4.0

Please let me know how to solve this issue

**Comment by lzzcd001** [comment]
Without further detailed error messages, I can only tell that there seems to be some compatibility issue  -- try check your GPU driver versions.

Related issue: https://github.com/NVlabs/nvdiffrecmc/issues/13

**Comment by sungmin9939** [comment]
my GPU is RTX 3090 and the driver version is 535.146.02
could relatively higher driver version be a problem?
it would be thankful if you can let me know name of your gpu hardware and driver version you used to implement gshell
