### ISSUE TITLE
reproduce nerf synthetic error: no attribute 'sdf_mlp_pretrain_steps'

### ISSUE THREAD

**Issue by j-cyoung** [lzzcd001/GShell#6]
Thanks for your excellent work! I encountered issues when reproducing the code on the `nerf synthetic` dataset.

Shell Command:

```shell
python train_gshelltet_synthetic.py --config configs/nerf_chair.json --o result/nerf_chair
```

Output:
```shell
...
../nerf_synthetic/chair
DatasetNERF: 100 images with shape [800, 800]
DatasetNERF: 200 images with shape [800, 800]
/opt/conda/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Cuda path /usr/local/cuda
End of OptiXStateWrapper 
using resolution 128
Traceback (most recent call last):
  File "train_gshelltet_synthetic.py", line 658, in <module>
    geometry = GShellTetsGeometry(FLAGS.gshell_grid, FLAGS.mesh_scale, FLAGS)
  File "/su_jy_user1/GShell/geometry/gshell_tets_geometry.py", line 85, in __init__
    for _ in trange(self.FLAGS.sdf_mlp_pretrain_steps):
AttributeError: 'Namespace' object has no attribute 'sdf_mlp_pretrain_steps'
OptiXStateWrapper destructor 
```
![image](https://github.com/lzzcd001/GShell/assets/54196410/45831d3b-bfff-4783-9161-0ad5a1c86f05)

I checked the file `gshell_tets_geometry.py` and `train_gshelltet_synthetic.py` , and I cannot find the definition of `FLAGS.sdf_mlp_pretrain_steps`, while I can find it in `train_gflexicubes_deepfashion.py`,  `train_gflexicubes_polycam.py`, `train_gshelltet_deepfashion.py`, `train_gshelltet_polycam.py`. **By the way, the setting in `train_gshelltet_deepfashion.py` seems a litter different from the others (which is $1000$ rather than $10000$), should I fix it?**

**Could you please provide the exact value of `FLAGS.sdf_mlp_pretrain_steps` about synthetic dataset? Thanks for your help!**

**Comment by lzzcd001** [comment]
Hey and thanks for pointing the issue out. We forgot to include the argument and do plan to further clean up the code very soon. For now, simply add the `sdf_mlp_pretrain_steps ` argument to `FLAGS`.

The exact value of `sdf_mlp_pretrain_steps` does not matter too much, as long as the grid is well initialized (initial shape close to a sphere with a rather smooth MLP). We picked the value of `10000` for convenience, but `1000` should suffice.
