### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by wishinghao** [lzzcd001/GShell#7]
Thank you for this stunning work! 
I am reading the code and have some questions.
Why does the rendering process use a _proj_mtx_ matrix? I understand that just using _scale_mat_ and _world_mat_ should be enough to render the mesh, similar to NeuS. Why does the code require an additional _proj_mtx_, and how can I obtain this _proj_mtx_ for my data?

**Comment by lzzcd001** [comment]
Good question! Rasterization is typically done by transforming mesh vertex coordinates into the so-called "clip space" in which step a view frustum is deformed into a cube (for instance, see Nvdiffrast doc [here](https://nvlabs.github.io/nvdiffrast/#rasterization), or some tutorials on camera projection). For this purpose, a projection matrix has to be multiplied.

Implementation-wise, `proj_mtx` is computed by (as in `dataset/dataset_deepfashion.py`)

```
self.proj_mtx = util.perspective(
            self.fovy, 
            self.FLAGS.display_res[1] / self.FLAGS.display_res[0], 
            self.FLAGS.cam_near_far[0], 
            self.FLAGS.cam_near_far[1]
)
```

Also note that, repos for NeRF, NeuS and many other volumetric rendering methods typically adopt the OpenCV convention, while Nvdiffrast adopts the OpenGL one. Therefore, the `y` and `z` axes have to be flipped for the camera poses, which is done by simply multiplying the following matrix:

```
flip_mat = torch.tensor([
            [ 1,  0,  0,  0],
            [ 0, -1,  0,  0],
            [ 0,  0, -1,  0],
            [ 0,  0,  0,  1]
        ], dtype=torch.float)
```
